### ISSUE TITLE
Resizing states graphically makes the change to the opposite direction

### ISSUE THREAD

**Issue by ahmadjbara** [ObjectProcessMethodology/OPCloud-client#4]
For some cases, pulling the edges of a state for enlarging/shrinking causes the change to occur in the opposite direction.
@dovdori 
@NataliLevi

**Comment by dovdori** [comment]
OK this looks good and we can use GIT for issue tracking.
Natali, I thought this issue was resolved but still in some cases it is there.

**Comment by NataliLevi** [comment]
It was resolved but I didn't like the way so I didn't insert it to the
git.  Anyway, most of the issues are I progress by me or by Oleg as part of
his project.  I'll try to insert today some corrections.

בתאריך 29 באפר׳ 2017 14:39,‏ "dovdori" <notifications@github.com> כתב:

OK this looks good and we can use GIT for issue tracking.
Natali, I thought this issue was resolved but still in some cases it is
there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ObjectProcessMethodology/OPCloud-client/issues/4#issuecomment-298163806>,
or mute the thread

**Comment by NataliLevi** [comment]
changed state type to dia.element
